const express = require('express')
const router = express.Router()
const {success,error,logout, login, forgotPassword, resetPassword} = require('../controller/auth')
const {getAllUsers, getUser, dashboard} = require('../controller/users')
const {isLoggedIn} = require('../middleware/loggedIn')
const {adminCheck} = require('../middleware/loggedIn')
const authenticationMiddleware = require('../middleware/jwtauth')
router.route('/dashboard').get(authenticationMiddleware,dashboard)
router.route('/success').get(isLoggedIn,success)
router.route('/error').get(error)
router.route('/logout').get(logout)
router.route('/').get(authenticationMiddleware,adminCheck,getAllUsers)
router.route('/:id').get(authenticationMiddleware,adminCheck,getUser)
router.route('/login').post(login)
router.route('/forgot-password').post(forgotPassword)
router.route('/reset-password/:token').post(resetPassword)

module.exports = router